repos:
  - repo: meta
    hooks:
      - id: check-hooks-apply
      - id: check-useless-excludes

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-added-large-files
      - id: check-toml
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
        args: ['--markdown-linebreak-ext=md,markdown']

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.3
    hooks:
      - id: ruff
        args: [--fix]
        exclude: |
          (?x)^(
              shell_script/.*|
              TOOLS/.*
          )$
      - id: ruff-format
        exclude: |
          (?x)^(
              shell_script/.*|
              TOOLS/.*
          )$

ci:
  autoupdate_schedule: monthly
