name: CI

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

jobs:
  test-cf:
    name: Test (conda-forge dependencies)
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: mamba-org/setup-micromamba@v1
        with:
          environment-file: environment-dev.yml
          cache-environment: true

      - name: Install qtrack
        run: pip install -e . --no-deps

      - name: pytest
        run: pytest -v

  test-pip:
    name: Test (PyPI dependencies)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          cache: pip

      - name: Install qtrack
        run: pip install .[test]

      - name: pytest
        run: pytest -v
