name: CI

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: mamba-org/setup-micromamba@v1
        with:
          environment-file: environment-dev.yml
          cache-environment: true

      - name: Install qtrack
        run: pip install -e . --no-deps

      - name: pytest
        run: pytest -v
